### ISSUE TITLE
create sorting algorithm 

### ISSUE THREAD

**Issue by balbhimk** [balbhimk/hactoberfest_2021#1]
add sorting algorithm 
but same sorting algorithm should not be included in this repository
How to name your file?
Take today's date, i.e. 2ndOct
Take your GitHUB username id like  "xyzboy", etc or anything which you have.
if File extension = ".cpp" in this issue.
Combine all 3 to get your file name : Date + "_" + Username + File Extension, ex. "2ndOct_xyzboy.cpp". Create this file in above mentioned folder only 

if java then u have to make file in different way
you have to add sorting algorithm name after that user name 
Ex- if GIT user name is "xyzboy" and algorithm is bubble sort then file name is "bubblesort_xyzboy.java"

please add file as per folder name if c++ program then add file in cpp-sorting_algo
if java program then add file in java-sorting_algo folder

**Comment by Perpetual-Incantation** [comment]
please assign this issue to me.

**Comment by balbhimk** [comment]
> please assign this issue to me.

issue is closed now try after some time with another issue
