### ISSUE TITLE
Form 

### ISSUE THREAD

**Issue by ASLManasa** [balbhimk/hactoberfest_2021#34]
Hi, I am a participant of Hacktoberfest. I would like to add a form using html css. Kindly assign me this issue. Thank you.

**Comment by kinzahabib44** [comment]
Hi, I am a participant of Hacktoberfest. I would like to add a form using html CSS. Kindly assign me this issue. Thank you.

**Comment by harshvardhan614** [comment]
@balbhimk  sir, I make a form with help of HTML, CSS. Can you assign this issue to me? I loved to work on it.

**Comment by balbhimk** [comment]
@harshvardhan614 @kinzahabib44 hello no need of assignment just do push request it will be merged if it will be valid PR
